{% set name = "pylink-square" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylink-square-{{ version }}.tar.gz
  sha256: ff807532f7a615193f4ecc7f969287a51383f32fdd41cfa2694822c4b16e9721

build:
  entry_points:
    - pylink = pylink.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - behave
    - coverage
    - pip
    - psutil
    - pypandoc
    - python
  run:
    - future
    - psutil >=5.2.2
    - python
    - six

test:
  imports:
    - pylink
  commands:
    - pip check
    - pylink --help
  requires:
    - pip

about:
  home: http://www.github.com/Square/pylink
  summary: Python interface for SEGGER J-Link.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rudispr
