{% set name = "pylink-square" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4b84b5fd1c22546189324e0ac6c716eb67a90bf7c18dfe50450924a4055bc348

build:
  entry_points:
    - pylink = pylink.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - behave
    - coverage
    - pip
    - psutil
    - pypandoc
    - python
  run:
    - future
    - psutil >=5.2.2
    - python
    - six

test:
  imports:
    - pylink
  commands:
    - pip check
    - pylink --help
  requires:
    - pip

about:
  home: http://www.github.com/Square/pylink
  summary: Python interface for SEGGER J-Link.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rudispr
