{% set name = "pylink-square" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylink-square-{{ version }}.tar.gz
  sha256: 12d6b03f39a2a70beb1d4df08cc7b464bc7518a9131e498f1e4055236044d4ac

build:
  entry_points:
    - pylink = pylink.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - behave
    - coverage
    - pip
    - psutil
    - pypandoc
    - python
  run:
    - future
    - psutil >=5.2.2
    - python
    - six

test:
  imports:
    - pylink
  commands:
    - pip check
    - pylink --help
  requires:
    - pip

about:
  home: http://www.github.com/Square/pylink
  summary: Python interface for SEGGER J-Link.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rudispr
