{% set name = "pylink-square" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5dae5fd211420d844b54f47d4f79965ca9f524b922cb0cc428a75674b71b4ec6

build:
  entry_points:
    - pylink = pylink.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - psutil
    - six
    - coverage
    - pip
    - setuptools
  run:
    - python
    - psutil >=5.2.2
    - six

test:
  imports:
    - pylink
  commands:
    - pip check
    - pylink --help
  requires:
    - pip

about:
  home: http://www.github.com/Square/pylink
  summary: Python interface for SEGGER J-Link.
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - tests/functional/features/jlink/license.feature
    - tests/functional/features/steps/licenses.py

extra:
  recipe-maintainers:
    - rudispr
