{% set name = "pylink-square" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fe5a0a148cdcd234387c73cbc1c6c2ffb84a8ba96f183f0285d9946f5f9533a

build:
  entry_points:
    - pylink = pylink.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - behave
    - coverage
    - pip
    - psutil
    - pypandoc
    - python
  run:
    - future
    - psutil >=5.2.2
    - python
    - six

test:
  imports:
    - pylink
  commands:
    - pip check
    - pylink --help
  requires:
    - pip

about:
  home: http://www.github.com/Square/pylink
  summary: Python interface for SEGGER J-Link.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rudispr
